[project]
name = "timscam-queue-estimator"
version = "0.1.0"
description = "A project to take in a m3u8 playlist / stream and gather info about the number of people"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "opencv-python>=4.13.0.90",
    "openvino>=2025.4.1",
]
